# Script to Parse the XML test report generated by CasperJS

library("XML")
path = "~/Desktop/rep" # set the location of xml files
file.names <- dir(path, pattern =".xml")
print(file.names)
D=data.frame("Package", 'Name',"Time", "Failures",'Status')
for (k in 1:length(file.names))
{
doc<-xmlTreeParse(file.names[k])
top<-xmlRoot(doc)
z=names(top)
testcases<-length(z)
package=c()
name=c()
failures=c()
time=c()
for (i in 1:length(z))
{
b<-xmlAttrs(top[[i]])
package=c(package,b['package'])
name=c(name,b['name'])
failures=c(failures, b['failures'])
time=c(time,b['time'])
}
status=c()
df<-data.frame(package, name, time, failures)
status<-function(val){
    if (val == 0 ){
        status=c(status,'Pass')
    }
    else{
        status=c(status,'Fail')
    }
}
#lapply(list(df['failures']), status)

status<-function(val){
    if (val != 0 ){
        return ('Fail')
    }
    else{
        return ('Pass')
    }
}
status<-apply(df['failures'],1,FUN= status)
df<-cbind(df,status)
D=rbind(as.matrix(D),as.matrix(df))
# print(df)
}
# warnings()
write.csv(file="result.csv",D)
